### PR TITLE
Ansible installation for UCS Traffic Monitoring (UTM)

### PR DESCRIPTION
**Pull request by bouthib**
Hi,

I don't know if you could have some interest into an ansible automation script to install the required stack to run UTM.

I did saw your comment about building an OVA with every release.  I feel your pain (been there, done that).

So I did build that ansible-install script to allow to install from scratch UTM without manual steps.  However, I also saw that you now provide upgrade_utm.sh (Kiara) so I don't know how you see this proposed contribution.

So let me know if you think that still could be usefull or if you have any ideas about it.

If you think you will accept that feature, please let me know.  I could update the https://github.com/VilledeMontreal/ucs_traffic_monitor/blob/feature/ansible-install/ansible-install/README.md to all the image references to your github repository (or again, if you see this otherwise).

Regards,

P.S. : Again, if this is not way to proceed, please let me know. This is all new to me.

### CODE REVIEW

**Comment by paregupt** [comment]
Ansible will be cool but nobody asked me yet. Most of the folks just want an OVA, to get up and running without worrying about the underlying details. I realized that I won't be able to create OVA with every release. upgrade_utm.sh (Kiara) is an alternative. Feel free if you wish to add Ansible installation option. I am sure it will be of use for some folks in the future.

Also, I am not the best person to review/approve changes on Ansible. If you want, please maintain a fork of the repo with Ansible support. I can add a link to your fork for the folks looking for this option. 

Let me know what works best for you. Thank you again.

**Comment by andrico21** [comment]
@paregupt  just my 2 cents: we're using Hyper-V here so no easy OVA way for us... but anyway Ansible is appreciated considering some options need to be customized (DB name for example since I'm not using default 'telegraf' DB name).
p.s. Great job anyway!

**Comment by bouthib** [comment]
No problem with what you propose. We can see where it will go from there.  Since everything (and this is really not big) is in the ansible-install folder, if you ever want to "merge it", let met know.  I was also thinking that you could use it to build the OVA.

I'm waiting on somes others peoples internally (I'm not git / github savvy enough) to know if that should remain on a feature branch or be merge on master on our side.  I will also look into the possibility of enabling the "Issues" feature on our side on github).

@andrico21 : When we know where the "Issues" should go, I would be very interested in knowing what you would like to see as customizable.

**Comment by paregupt** [comment]
@andrico21 Changing DB name is a one line change in telegraf.conf. 

@bouthib 
As mentioned above, I won't be able to maintain this section of code. In the future, if issues/requests are raised, I won't be able to support them. I you wish, you can take up such issues.
Overall, this is a great addition. I appreciate your contribution. 

You may please go ahead and merge.

**Comment by andrico21** [comment]
@paregupt yes, but I'm talking about changing it in dashboards also, there are "DB" variable in all dashboards so changing it a bit tricky when you're already deployed it :) also it's hardcoded in some sections (values in dashboards "templating")

**Comment by paregupt** [comment]
@andrico21 good point

**Pull request merged**
