### PR TITLE
Fixed to allow to deploy UTM on Linux 8 (ansible-install)

### PR DESCRIPTION
**Pull request by bouthib**
Hi,

This allow to use ansible-install on Linux 7 or 8 (tested on CentOS7 / OL8).  I did also add the possibility of using influxdb2.x (this is not the default). I also add a reference to ansible-install from the UTM main readme.

I did not open a issue since it was not really really one with UTM itself. Just let me know if you want me to proceed otherwise.

Regards,

### CODE REVIEW

**Comment by paregupt** [comment]
Hi Benoit, all looks good and most of the changes are under ansible install anyway. Regarding InfluxDB 2.x, how you done any testing? Based on my previous research, it needs Flux, a new language. Although, InfluxQL may be used with InfluxDB 2.0, it needs testing cycles which I did not have. Wondering if you soaked it enough?

If not, I suggest bringing in InfluxDB 2.0 only after it's fully baked. Let me know what you think.

**Comment by bouthib** [comment]
Hi Paresh,

Hope you are doing well.

I did a full deployement within our environement using influxdb2 using InfluxQL.  I can't pretend that I have tested everything beside looking at the grafana dashboards and the telegraf log file.

From the inventory file, a user could control if he want to deploy with v1 or v2 (defaulted to v1):

InfluxDB version (via package name : influxdb is v1, influxdb2 is v2)
influxdb_package=influxdb

Do you prefer that I remove any references (and the variable) to influxdb2?  Or maybe adding a clear warning message that changing that variable to v2 is experimental / for testing purpose ?

Let me know what you think as well ;-)

**Comment by paregupt** [comment]
Hi Benoit, sorry for the delay. Because so many customers are using UTM in production, I am being very defensive in making changes to the core infra of it. My thought is that we bring in InfluxDB 2.0 with flux together and bake this change enough. Just bringing InfluxDB 2.0 alone may expose some bugs. I don't have cycles to test it for a few months. Maybe after a few months, we can collectively make the changes and test them out. If you agree, maybe check in the other changes without flux/influx2.0 changes.

**Comment by bouthib** [comment]
Hi Paresh,

No problem.  I get it, we all have day job (delay) !

No problem with your position.  I will remove all the changes that allow InfluxDB 2.0 to be install (including the code for the update procedure).

I will open a new PR if needed.

**Comment by bouthib** [comment]
Hi Paresh,

The PR does not contain anything related to InfluxDB 2.0 anymore (deployement has been tested again on CentOS7 and Oracle Linux 8).

Please let me know.

**Review by paregupt — APPROVED** [review]

**Comment by paregupt** [comment]
All good. Please go ahead and check-in the code. And thank you so much for contributing to this project.

**Pull request merged**
